### ISSUE TITLE
A big thank you from the Paymill dev team!

### ISSUE THREAD

**Issue by d0mme-zz** [komola/paymill-node#3]
Hi guys,

no really issue, just in order to speak for all our dev members from Paymill: 

Thanks for the great work, keep it up. We will mention you in our new blog posts and of course on our site!

With best wishes,
Dominic Krasnopolski

**Comment by thomaschaaf** [comment]
Hey Dominic,

No problem ;)
More examples coming soon. Is there an api key I can use/publish and let others use?

You should mention us here :wink: https://www.paymill.com/de-de/dokumentation/referenz/api-bibliotheken/index.html

Grüße aus Braunschweig

**Comment by extronics** [comment]
Hi Thomas,

there isn't a generic test / example key if that's what you are looking for. So you'll have to use any random string for code samples.

Grüße aus München ;)
