### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by Prinzhorn** [komola/paymill-node#9]
I don't feel comfortable using this library or even sending sending pull-requests, when there are no tests.

I guess we could test every single entity, except for `payments` (due to missing `token`). But if we create a payment once, we could hard code it's `id` into the tests.

If we can agree on a framework and test runner, I'd happily contribute to it.

Also: It'd be great to have a `.jshintrc` file. Currently the main.js is not lint free.

**Comment by Prinzhorn** [comment]
After thinking about it, we can test _all_ entities. We don't need to actually send a request to paymill, we can just use https://github.com/flatiron/nock to simulate it. Because we don't want to test if paymill works (it does, I hope :-D), but only if `paymill-node` sends the right stuff and reacts correctly.

**Comment by sebastianhoitz** [comment]
Unit tests were introduced by @nponiros in his awesome pull request :+1:
